name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du Code
        uses: actions/checkout@v4

      - name: Contrôle des dépendances avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: 'requirements.txt'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'table'
          output: 'trivy-dependencies-report.txt'

      - name: Upload rapport dépendances
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dependencies-report
          path: trivy-dependencies-report.txt

      - name: Résultat du contrôle
        run: echo "Scan des dépendances terminé. Rapport disponible en artifact."

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout du Code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          echo "Construction de l'image Docker pour analyse..."
          docker build -t mon-image-test:latest .

      - name: Installer Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scanner l'image Docker avec Trivy
        run: |
          trivy image \
            --severity CRITICAL,HIGH,MEDIUM,LOW \
            --format table \
            --output trivy-image-report.txt \
            mon-image-test:latest

      - name: Upload rapport image Docker
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.txt

      - name: Résultat du scan image
        run: echo "Scan de l'image terminé. Rapport disponible en artifact."

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Application prête à être déployée."
